version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: sqlite:///data.db
    depends_on:
      - redis

  worker:
    build: .
    command: rq worker email
    volumes:
      - .:/app
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: sqlite:///data.db
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
